version: "3.1"

services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.enable=false"
    networks:
      - churrops
    deploy:
      replicas: 3
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

networks:
 churrops:
  driver: overlay
  ipam:
   config:
    - subnet: 192.168.0.0/24
